import 'dart:math';
import '../models/models.dart';

class DemoData {
  /// 12 demo providers across 3 service types
  static List<Provider> get providers => [
        Provider(
          providerId: 'dent-001',
          name: 'Bright Smile Dental',
          serviceType: 'dentist',
          phone: '+1-555-0101',
          rating: 4.7,
          address: '123 Oak Street, Downtown',
          latitude: 40.7128,
          longitude: -74.006,
          hours: 'Mon-Fri 8am-6pm',
        ),
        Provider(
          providerId: 'dent-002',
          name: 'City Dental Care',
          serviceType: 'dentist',
          phone: '+1-555-0102',
          rating: 4.3,
          address: '456 Elm Avenue, Midtown',
          latitude: 40.7549,
          longitude: -73.984,
          hours: 'Mon-Sat 9am-7pm',
        ),
        Provider(
          providerId: 'dent-003',
          name: 'Premier Dental Associates',
          serviceType: 'dentist',
          phone: '+1-555-0103',
          rating: 4.9,
          address: '789 Pine Road, Uptown',
          latitude: 40.7831,
          longitude: -73.9712,
          hours: 'Mon-Fri 7am-5pm',
        ),
        Provider(
          providerId: 'dent-004',
          name: 'Affordable Dental Group',
          serviceType: 'dentist',
          phone: '+1-555-0104',
          rating: 4.1,
          address: '321 Maple Lane, Westside',
          latitude: 40.7282,
          longitude: -74.0776,
          hours: 'Mon-Fri 8am-5pm, Sat 9am-1pm',
        ),
        Provider(
          providerId: 'dent-005',
          name: 'Harmony Dental Wellness',
          serviceType: 'dentist',
          phone: '+1-555-0105',
          rating: 4.5,
          address: '654 Cedar Blvd, Eastside',
          latitude: 40.7214,
          longitude: -73.9456,
          hours: 'Tue-Sat 10am-7pm',
        ),
        Provider(
          providerId: 'mech-001',
          name: 'FastFix Auto Shop',
          serviceType: 'mechanic',
          phone: '+1-555-0201',
          rating: 4.4,
          address: '100 Industrial Parkway',
          latitude: 40.6892,
          longitude: -74.0445,
          hours: 'Mon-Sat 7am-6pm',
        ),
        Provider(
          providerId: 'mech-002',
          name: "Tony's Garage & Auto",
          serviceType: 'mechanic',
          phone: '+1-555-0202',
          rating: 4.8,
          address: '250 Workshop Drive',
          latitude: 40.7044,
          longitude: -74.0132,
          hours: 'Mon-Fri 8am-5pm',
        ),
        Provider(
          providerId: 'mech-003',
          name: 'QuickLube Express',
          serviceType: 'mechanic',
          phone: '+1-555-0203',
          rating: 3.9,
          address: '875 Service Road',
          latitude: 40.7433,
          longitude: -73.9915,
          hours: 'Mon-Sun 7am-8pm',
        ),
        Provider(
          providerId: 'salon-001',
          name: 'Luxe Hair Studio',
          serviceType: 'salon',
          phone: '+1-555-0301',
          rating: 4.6,
          address: '42 Fashion Ave',
          latitude: 40.7527,
          longitude: -73.9772,
          hours: 'Tue-Sun 10am-8pm',
        ),
        Provider(
          providerId: 'salon-002',
          name: 'The Cutting Edge',
          serviceType: 'salon',
          phone: '+1-555-0302',
          rating: 4.2,
          address: '88 Style Street',
          latitude: 40.7362,
          longitude: -73.9897,
          hours: 'Mon-Sat 9am-7pm',
        ),
        Provider(
          providerId: 'salon-003',
          name: 'Bella Rosa Salon & Spa',
          serviceType: 'salon',
          phone: '+1-555-0303',
          rating: 4.8,
          address: '15 Wellness Way',
          latitude: 40.7681,
          longitude: -73.9644,
          hours: 'Wed-Mon 11am-9pm',
        ),
        Provider(
          providerId: 'salon-004',
          name: 'UrbanClips Barbershop',
          serviceType: 'salon',
          phone: '+1-555-0304',
          rating: 4.0,
          address: '200 Main Street',
          latitude: 40.7195,
          longitude: -74.0002,
          hours: 'Mon-Sat 8am-6pm',
        ),
      ];

  /// Calendar busy slots
  static List<Map<String, String>> get busySlots => [
        {'start': '2026-02-09T09:00:00', 'end': '2026-02-09T10:30:00', 'title': 'Team Standup + Sprint Planning'},
        {'start': '2026-02-09T14:00:00', 'end': '2026-02-09T15:00:00', 'title': 'Client Call'},
        {'start': '2026-02-10T11:00:00', 'end': '2026-02-10T12:00:00', 'title': 'Lunch with Sarah'},
        {'start': '2026-02-10T16:00:00', 'end': '2026-02-10T17:30:00', 'title': 'Workshop'},
        {'start': '2026-02-11T08:00:00', 'end': '2026-02-11T09:00:00', 'title': 'Morning Gym'},
        {'start': '2026-02-11T13:00:00', 'end': '2026-02-11T14:00:00', 'title': 'Dentist Follow-up'},
        {'start': '2026-02-12T10:00:00', 'end': '2026-02-12T11:30:00', 'title': 'All Hands Meeting'},
        {'start': '2026-02-13T09:00:00', 'end': '2026-02-13T10:00:00', 'title': '1:1 with Manager'},
      ];

  /// Receptionist transcript templates
  static List<Map<String, dynamic>> get scenarios => [
        {
          'outcome': 'available',
          'notes': 'Immediate availability',
          'transcript': [
            'Receptionist: Thank you for calling {provider}, how can I help you?',
            'Agent: Hi, I\'m calling to schedule a {service} appointment for my client this week.',
            'Receptionist: Of course! Let me check our schedule... We have openings this week.',
            'Agent: That sounds great. What times are available?',
            'Receptionist: We have a slot available. Shall I book that for you?',
            'Agent: Let me check my client\'s calendar first... Yes, that works perfectly.',
            'Receptionist: Wonderful! I\'ll pencil that in.',
          ],
        },
        {
          'outcome': 'available',
          'notes': 'Multiple slots after hold',
          'transcript': [
            'Receptionist: {provider}, good morning!',
            'Agent: Hello, I\'d like to book a {service} appointment this week please.',
            'Receptionist: Sure thing! Could you hold for just a moment?',
            'Agent: Of course, take your time.',
            'Receptionist: Thank you for holding. I have several openings this week.',
            'Agent: Perfect, could you tell me what\'s available?',
            'Receptionist: I have a few options — which works best for your schedule?',
          ],
        },
        {
          'outcome': 'available',
          'notes': 'Limited — one slot',
          'transcript': [
            'Receptionist: {provider}, how may I direct your call?',
            'Agent: Hi, I\'m looking to schedule a {service} appointment.',
            'Receptionist: We\'re quite booked this week, but let me see...',
            'Agent: I appreciate you checking.',
            'Receptionist: You\'re in luck! We had a cancellation. One slot left.',
            'Agent: Let me confirm it works with my client\'s schedule.',
            'Receptionist: Please do — it\'ll go fast!',
          ],
        },
        {
          'outcome': 'available',
          'notes': 'New patient welcome',
          'transcript': [
            'Receptionist: Welcome to {provider}! First time calling us?',
            'Agent: Yes, calling for a new patient {service} appointment.',
            'Receptionist: We love new patients! Extra time allocated for first visits.',
            'Agent: What do you have available?',
            'Receptionist: Let me check... Yes, we have availability this week.',
            'Agent: Excellent, checking my client\'s calendar now.',
            'Receptionist: Take your time! We\'ll reserve it for 10 minutes.',
          ],
        },
        {
          'outcome': 'available',
          'notes': 'Morning only',
          'transcript': [
            'Receptionist: {provider}, good afternoon.',
            'Agent: I need to schedule a {service} appointment this week.',
            'Receptionist: We have morning availability only this week.',
            'Agent: Morning works. What specific times?',
            'Receptionist: We can do early morning — would that work?',
            'Agent: Let me verify... Yes, that\'s clear.',
            'Receptionist: Perfect, I\'ll mark it down.',
          ],
        },
        {
          'outcome': 'available',
          'notes': 'Same-day availability',
          'transcript': [
            'Receptionist: {provider} emergency line, how can I help?',
            'Agent: I need a same-day {service} appointment if possible.',
            'Receptionist: Let me check our emergency slots... Yes! We can fit you in.',
            'Agent: That\'s incredible. What time?',
            'Receptionist: We have a same-day slot available right now.',
            'Agent: Checking calendar... That\'s wide open!',
            'Receptionist: Perfect. Please bring ID and insurance card.',
          ],
        },
        {
          'outcome': 'available',
          'notes': 'Evening availability',
          'transcript': [
            'Receptionist: {provider}, evening appointments desk.',
            'Agent: Do you have any evening {service} appointments this week?',
            'Receptionist: Yes! Extended hours on Tuesdays and Thursdays.',
            'Agent: What times are open?',
            'Receptionist: We have evening slots later this week.',
            'Agent: Let me verify... My client is free then!',
            'Receptionist: Wonderful. See you during evening hours.',
          ],
        },
        {
          'outcome': 'available',
          'notes': 'Weekend slots',
          'transcript': [
            'Receptionist: You\'ve reached {provider}.',
            'Agent: Looking to book a {service} appointment. Anything this week?',
            'Receptionist: Weekdays are full, but we have Saturday openings.',
            'Agent: Saturday could work. What times?',
            'Receptionist: A couple of Saturday slots available.',
            'Agent: Checking if that\'s free... Looks good!',
            'Receptionist: Great! We\'ll see you then.',
          ],
        },
        {
          'outcome': 'unavailable',
          'notes': 'Fully booked',
          'transcript': [
            'Receptionist: {provider}, how can I help?',
            'Agent: I need a {service} appointment this week.',
            'Receptionist: I\'m sorry, we\'re completely booked through the end of the week.',
            'Agent: Nothing at all? Even a cancellation slot?',
            'Receptionist: Unfortunately no. Next opening is in two weeks.',
            'Agent: I see. Thank you for checking.',
            'Receptionist: You\'re welcome. Would you like a waitlist spot?',
          ],
        },
        {
          'outcome': 'unavailable',
          'notes': 'Provider on vacation',
          'transcript': [
            'Receptionist: {provider}, good morning.',
            'Agent: I\'d like to schedule a {service} appointment.',
            'Receptionist: The doctor is on vacation this week and next.',
            'Agent: Is there another provider available?',
            'Receptionist: Not for that service. Regular hours resume in two weeks.',
            'Agent: Understood, thank you.',
            'Receptionist: Feel free to call back then!',
          ],
        },
        {
          'outcome': 'unavailable',
          'notes': 'System down',
          'transcript': [
            'Receptionist: {provider}.',
            'Agent: I need to book a {service} appointment.',
            'Receptionist: Our scheduling system is currently down for maintenance.',
            'Agent: When will it be back?',
            'Receptionist: Tomorrow afternoon.',
            'Agent: I\'ll try again later.',
            'Receptionist: Sorry for the inconvenience.',
          ],
        },
        {
          'outcome': 'callback',
          'notes': 'Need to call back',
          'transcript': [
            'Receptionist: {provider}, please hold... Thank you for waiting.',
            'Agent: I\'d like to book a {service} appointment this week.',
            'Receptionist: Can I take your number and call back in 30 minutes?',
            'Agent: I\'d prefer to hold if possible.',
            'Receptionist: I can\'t confirm anything right now. Let me call you back.',
            'Agent: Alright. Thank you.',
            'Receptionist: We\'ll get back to you within the hour!',
          ],
        },
      ];

  static List<Provider> getProvidersByType(String serviceType) {
    return providers
        .where((p) => p.serviceType.toLowerCase() == serviceType.toLowerCase())
        .toList();
  }
}
